// <auto-generated />
using System;
using System.Text.Json;
using Database.Data;
using Database.Enumerations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230126153325_RenameXminToVersion")]
    partial class RenameXminToVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("database")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "data_kind", new[] { "calorimetric_data", "hygrothermal_data", "optical_data", "photovoltaic_data" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.Data.CalorimetricData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double[]>("GValues")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double[]>("UValues")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string[]>("Warnings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("calorimetric_data", "database");
                });

            modelBuilder.Entity("Database.Data.GetHttpsResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CalorimetricDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataFormatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HygrothermalDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OpticalDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhotovoltaicDataId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CalorimetricDataId");

                    b.HasIndex("HygrothermalDataId");

                    b.HasIndex("OpticalDataId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PhotovoltaicDataId");

                    b.ToTable("get_https_resource", "database");
                });

            modelBuilder.Entity("Database.Data.HygrothermalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string[]>("Warnings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("hygrothermal_data", "database");
                });

            modelBuilder.Entity("Database.Data.OpticalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double[]>("ColorRenderingIndices")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double[]>("InfraredEmittances")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double[]>("NearnormalHemisphericalSolarReflectances")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double[]>("NearnormalHemisphericalSolarTransmittances")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double[]>("NearnormalHemisphericalVisibleReflectances")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double[]>("NearnormalHemisphericalVisibleTransmittances")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string[]>("Warnings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("optical_data", "database");
                });

            modelBuilder.Entity("Database.Data.PhotovoltaicData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string[]>("Warnings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("photovoltaic_data", "database");
                });

            modelBuilder.Entity("Database.Data.CalorimetricData", b =>
                {
                    b.OwnsOne("Database.Data.AppliedMethod", "AppliedMethod", b1 =>
                        {
                            b1.Property<Guid>("CalorimetricDataId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MethodId")
                                .HasColumnType("uuid");

                            b1.HasKey("CalorimetricDataId");

                            b1.ToTable("calorimetric_data", "database");

                            b1.WithOwner()
                                .HasForeignKey("CalorimetricDataId");

                            b1.OwnsMany("Database.Data.NamedMethodArgument", "Arguments", b2 =>
                                {
                                    b2.Property<Guid>("AppliedMethodCalorimetricDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<JsonDocument>("Value")
                                        .IsRequired()
                                        .HasColumnType("jsonb");

                                    b2.HasKey("AppliedMethodCalorimetricDataId", "Id");

                                    b2.ToTable("calorimetric_data_Arguments", "database");

                                    b2.WithOwner()
                                        .HasForeignKey("AppliedMethodCalorimetricDataId");
                                });

                            b1.OwnsMany("Database.Data.NamedMethodSource", "Sources", b2 =>
                                {
                                    b2.Property<Guid>("AppliedMethodCalorimetricDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("AppliedMethodCalorimetricDataId", "Id");

                                    b2.ToTable("calorimetric_data_Sources", "database");

                                    b2.WithOwner()
                                        .HasForeignKey("AppliedMethodCalorimetricDataId");

                                    b2.OwnsOne("Database.Data.CrossDatabaseDataReference", "Value", b3 =>
                                        {
                                            b3.Property<Guid>("NamedMethodSourceAppliedMethodCalorimetricDataId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("NamedMethodSourceId")
                                                .HasColumnType("integer");

                                            b3.Property<Guid>("DataId")
                                                .HasColumnType("uuid");

                                            b3.Property<DataKind>("DataKind")
                                                .HasColumnType("data_kind");

                                            b3.Property<DateTime>("DataTimestamp")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<Guid>("DatabaseId")
                                                .HasColumnType("uuid");

                                            b3.HasKey("NamedMethodSourceAppliedMethodCalorimetricDataId", "NamedMethodSourceId");

                                            b3.ToTable("calorimetric_data_Sources", "database");

                                            b3.WithOwner()
                                                .HasForeignKey("NamedMethodSourceAppliedMethodCalorimetricDataId", "NamedMethodSourceId");
                                        });

                                    b2.Navigation("Value")
                                        .IsRequired();
                                });

                            b1.Navigation("Arguments");

                            b1.Navigation("Sources");
                        });

                    b.OwnsMany("Database.Data.DataApproval", "Approvals", b1 =>
                        {
                            b1.Property<Guid>("CalorimetricDataId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ApproverId")
                                .HasColumnType("uuid");

                            b1.Property<string>("KeyFingerprint")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Query")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Response")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Signature")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CalorimetricDataId", "Id");

                            b1.ToTable("calorimetric_data_Approvals", "database");

                            b1.WithOwner()
                                .HasForeignKey("CalorimetricDataId");
                        });

                    b.Navigation("AppliedMethod")
                        .IsRequired();

                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("Database.Data.GetHttpsResource", b =>
                {
                    b.HasOne("Database.Data.CalorimetricData", "CalorimetricData")
                        .WithMany("Resources")
                        .HasForeignKey("CalorimetricDataId");

                    b.HasOne("Database.Data.HygrothermalData", "HygrothermalData")
                        .WithMany("Resources")
                        .HasForeignKey("HygrothermalDataId");

                    b.HasOne("Database.Data.OpticalData", "OpticalData")
                        .WithMany("Resources")
                        .HasForeignKey("OpticalDataId");

                    b.HasOne("Database.Data.GetHttpsResource", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("Database.Data.PhotovoltaicData", "PhotovoltaicData")
                        .WithMany("Resources")
                        .HasForeignKey("PhotovoltaicDataId");

                    b.OwnsMany("Database.Data.FileMetaInformation", "ArchivedFilesMetaInformation", b1 =>
                        {
                            b1.Property<Guid>("GetHttpsResourceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("DataFormatId")
                                .HasColumnType("uuid");

                            b1.Property<string[]>("Path")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("GetHttpsResourceId", "Id");

                            b1.ToTable("FileMetaInformation", "database");

                            b1.WithOwner()
                                .HasForeignKey("GetHttpsResourceId");
                        });

                    b.OwnsOne("Database.Data.ToTreeVertexAppliedConversionMethod", "AppliedConversionMethod", b1 =>
                        {
                            b1.Property<Guid>("GetHttpsResourceId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MethodId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("GetHttpsResourceId");

                            b1.ToTable("get_https_resource", "database");

                            b1.WithOwner()
                                .HasForeignKey("GetHttpsResourceId");

                            b1.OwnsMany("Database.Data.NamedMethodArgument", "Arguments", b2 =>
                                {
                                    b2.Property<Guid>("ToTreeVertexAppliedConversionMethodGetHttpsResourceId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<JsonDocument>("Value")
                                        .IsRequired()
                                        .HasColumnType("jsonb");

                                    b2.HasKey("ToTreeVertexAppliedConversionMethodGetHttpsResourceId", "Id");

                                    b2.ToTable("get_https_resource_Arguments", "database");

                                    b2.WithOwner()
                                        .HasForeignKey("ToTreeVertexAppliedConversionMethodGetHttpsResourceId");
                                });

                            b1.Navigation("Arguments");
                        });

                    b.Navigation("AppliedConversionMethod");

                    b.Navigation("ArchivedFilesMetaInformation");

                    b.Navigation("CalorimetricData");

                    b.Navigation("HygrothermalData");

                    b.Navigation("OpticalData");

                    b.Navigation("Parent");

                    b.Navigation("PhotovoltaicData");
                });

            modelBuilder.Entity("Database.Data.HygrothermalData", b =>
                {
                    b.OwnsOne("Database.Data.AppliedMethod", "AppliedMethod", b1 =>
                        {
                            b1.Property<Guid>("HygrothermalDataId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MethodId")
                                .HasColumnType("uuid");

                            b1.HasKey("HygrothermalDataId");

                            b1.ToTable("hygrothermal_data", "database");

                            b1.WithOwner()
                                .HasForeignKey("HygrothermalDataId");

                            b1.OwnsMany("Database.Data.NamedMethodArgument", "Arguments", b2 =>
                                {
                                    b2.Property<Guid>("AppliedMethodHygrothermalDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<JsonDocument>("Value")
                                        .IsRequired()
                                        .HasColumnType("jsonb");

                                    b2.HasKey("AppliedMethodHygrothermalDataId", "Id");

                                    b2.ToTable("hygrothermal_data_Arguments", "database");

                                    b2.WithOwner()
                                        .HasForeignKey("AppliedMethodHygrothermalDataId");
                                });

                            b1.OwnsMany("Database.Data.NamedMethodSource", "Sources", b2 =>
                                {
                                    b2.Property<Guid>("AppliedMethodHygrothermalDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("AppliedMethodHygrothermalDataId", "Id");

                                    b2.ToTable("hygrothermal_data_Sources", "database");

                                    b2.WithOwner()
                                        .HasForeignKey("AppliedMethodHygrothermalDataId");

                                    b2.OwnsOne("Database.Data.CrossDatabaseDataReference", "Value", b3 =>
                                        {
                                            b3.Property<Guid>("NamedMethodSourceAppliedMethodHygrothermalDataId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("NamedMethodSourceId")
                                                .HasColumnType("integer");

                                            b3.Property<Guid>("DataId")
                                                .HasColumnType("uuid");

                                            b3.Property<DataKind>("DataKind")
                                                .HasColumnType("data_kind");

                                            b3.Property<DateTime>("DataTimestamp")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<Guid>("DatabaseId")
                                                .HasColumnType("uuid");

                                            b3.HasKey("NamedMethodSourceAppliedMethodHygrothermalDataId", "NamedMethodSourceId");

                                            b3.ToTable("hygrothermal_data_Sources", "database");

                                            b3.WithOwner()
                                                .HasForeignKey("NamedMethodSourceAppliedMethodHygrothermalDataId", "NamedMethodSourceId");
                                        });

                                    b2.Navigation("Value")
                                        .IsRequired();
                                });

                            b1.Navigation("Arguments");

                            b1.Navigation("Sources");
                        });

                    b.OwnsMany("Database.Data.DataApproval", "Approvals", b1 =>
                        {
                            b1.Property<Guid>("HygrothermalDataId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ApproverId")
                                .HasColumnType("uuid");

                            b1.Property<string>("KeyFingerprint")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Query")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Response")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Signature")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("HygrothermalDataId", "Id");

                            b1.ToTable("hygrothermal_data_Approvals", "database");

                            b1.WithOwner()
                                .HasForeignKey("HygrothermalDataId");
                        });

                    b.Navigation("AppliedMethod")
                        .IsRequired();

                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("Database.Data.OpticalData", b =>
                {
                    b.OwnsMany("Database.Data.CielabColor", "CielabColors", b1 =>
                        {
                            b1.Property<Guid>("OpticalDataId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("AStar")
                                .HasColumnType("double precision");

                            b1.Property<double>("BStar")
                                .HasColumnType("double precision");

                            b1.Property<double>("LStar")
                                .HasColumnType("double precision");

                            b1.HasKey("OpticalDataId", "Id");

                            b1.ToTable("CielabColor", "database");

                            b1.WithOwner()
                                .HasForeignKey("OpticalDataId");
                        });

                    b.OwnsOne("Database.Data.AppliedMethod", "AppliedMethod", b1 =>
                        {
                            b1.Property<Guid>("OpticalDataId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MethodId")
                                .HasColumnType("uuid");

                            b1.HasKey("OpticalDataId");

                            b1.ToTable("optical_data", "database");

                            b1.WithOwner()
                                .HasForeignKey("OpticalDataId");

                            b1.OwnsMany("Database.Data.NamedMethodArgument", "Arguments", b2 =>
                                {
                                    b2.Property<Guid>("AppliedMethodOpticalDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<JsonDocument>("Value")
                                        .IsRequired()
                                        .HasColumnType("jsonb");

                                    b2.HasKey("AppliedMethodOpticalDataId", "Id");

                                    b2.ToTable("optical_data_Arguments", "database");

                                    b2.WithOwner()
                                        .HasForeignKey("AppliedMethodOpticalDataId");
                                });

                            b1.OwnsMany("Database.Data.NamedMethodSource", "Sources", b2 =>
                                {
                                    b2.Property<Guid>("AppliedMethodOpticalDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("AppliedMethodOpticalDataId", "Id");

                                    b2.ToTable("optical_data_Sources", "database");

                                    b2.WithOwner()
                                        .HasForeignKey("AppliedMethodOpticalDataId");

                                    b2.OwnsOne("Database.Data.CrossDatabaseDataReference", "Value", b3 =>
                                        {
                                            b3.Property<Guid>("NamedMethodSourceAppliedMethodOpticalDataId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("NamedMethodSourceId")
                                                .HasColumnType("integer");

                                            b3.Property<Guid>("DataId")
                                                .HasColumnType("uuid");

                                            b3.Property<DataKind>("DataKind")
                                                .HasColumnType("data_kind");

                                            b3.Property<DateTime>("DataTimestamp")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<Guid>("DatabaseId")
                                                .HasColumnType("uuid");

                                            b3.HasKey("NamedMethodSourceAppliedMethodOpticalDataId", "NamedMethodSourceId");

                                            b3.ToTable("optical_data_Sources", "database");

                                            b3.WithOwner()
                                                .HasForeignKey("NamedMethodSourceAppliedMethodOpticalDataId", "NamedMethodSourceId");
                                        });

                                    b2.Navigation("Value")
                                        .IsRequired();
                                });

                            b1.Navigation("Arguments");

                            b1.Navigation("Sources");
                        });

                    b.OwnsMany("Database.Data.DataApproval", "Approvals", b1 =>
                        {
                            b1.Property<Guid>("OpticalDataId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ApproverId")
                                .HasColumnType("uuid");

                            b1.Property<string>("KeyFingerprint")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Query")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Response")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Signature")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("OpticalDataId", "Id");

                            b1.ToTable("optical_data_Approvals", "database");

                            b1.WithOwner()
                                .HasForeignKey("OpticalDataId");
                        });

                    b.Navigation("AppliedMethod")
                        .IsRequired();

                    b.Navigation("Approvals");

                    b.Navigation("CielabColors");
                });

            modelBuilder.Entity("Database.Data.PhotovoltaicData", b =>
                {
                    b.OwnsOne("Database.Data.AppliedMethod", "AppliedMethod", b1 =>
                        {
                            b1.Property<Guid>("PhotovoltaicDataId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MethodId")
                                .HasColumnType("uuid");

                            b1.HasKey("PhotovoltaicDataId");

                            b1.ToTable("photovoltaic_data", "database");

                            b1.WithOwner()
                                .HasForeignKey("PhotovoltaicDataId");

                            b1.OwnsMany("Database.Data.NamedMethodArgument", "Arguments", b2 =>
                                {
                                    b2.Property<Guid>("AppliedMethodPhotovoltaicDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<JsonDocument>("Value")
                                        .IsRequired()
                                        .HasColumnType("jsonb");

                                    b2.HasKey("AppliedMethodPhotovoltaicDataId", "Id");

                                    b2.ToTable("photovoltaic_data_Arguments", "database");

                                    b2.WithOwner()
                                        .HasForeignKey("AppliedMethodPhotovoltaicDataId");
                                });

                            b1.OwnsMany("Database.Data.NamedMethodSource", "Sources", b2 =>
                                {
                                    b2.Property<Guid>("AppliedMethodPhotovoltaicDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("AppliedMethodPhotovoltaicDataId", "Id");

                                    b2.ToTable("photovoltaic_data_Sources", "database");

                                    b2.WithOwner()
                                        .HasForeignKey("AppliedMethodPhotovoltaicDataId");

                                    b2.OwnsOne("Database.Data.CrossDatabaseDataReference", "Value", b3 =>
                                        {
                                            b3.Property<Guid>("NamedMethodSourceAppliedMethodPhotovoltaicDataId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("NamedMethodSourceId")
                                                .HasColumnType("integer");

                                            b3.Property<Guid>("DataId")
                                                .HasColumnType("uuid");

                                            b3.Property<DataKind>("DataKind")
                                                .HasColumnType("data_kind");

                                            b3.Property<DateTime>("DataTimestamp")
                                                .HasColumnType("timestamp with time zone");

                                            b3.Property<Guid>("DatabaseId")
                                                .HasColumnType("uuid");

                                            b3.HasKey("NamedMethodSourceAppliedMethodPhotovoltaicDataId", "NamedMethodSourceId");

                                            b3.ToTable("photovoltaic_data_Sources", "database");

                                            b3.WithOwner()
                                                .HasForeignKey("NamedMethodSourceAppliedMethodPhotovoltaicDataId", "NamedMethodSourceId");
                                        });

                                    b2.Navigation("Value")
                                        .IsRequired();
                                });

                            b1.Navigation("Arguments");

                            b1.Navigation("Sources");
                        });

                    b.OwnsMany("Database.Data.DataApproval", "Approvals", b1 =>
                        {
                            b1.Property<Guid>("PhotovoltaicDataId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ApproverId")
                                .HasColumnType("uuid");

                            b1.Property<string>("KeyFingerprint")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Query")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Response")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Signature")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("PhotovoltaicDataId", "Id");

                            b1.ToTable("photovoltaic_data_Approvals", "database");

                            b1.WithOwner()
                                .HasForeignKey("PhotovoltaicDataId");
                        });

                    b.Navigation("AppliedMethod")
                        .IsRequired();

                    b.Navigation("Approvals");
                });

            modelBuilder.Entity("Database.Data.CalorimetricData", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Database.Data.GetHttpsResource", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Database.Data.HygrothermalData", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Database.Data.OpticalData", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Database.Data.PhotovoltaicData", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
