START TRANSACTION;

CREATE TABLE database."DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text NULL,
    "Xml" text NULL,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230210135413_AddDataProtectionKeys', '7.0.2');

COMMIT;

